mlname: "Editing team"
description: Repo Edit
title: "[Repo Edit Forn]:"
labels: ["form", "request", "edit"]
body:
  - type: input
    id: reponame
    attributes:
      label: Repository Name
      description: Your Repository Name
      placeholder: repo-name
    validations:
      required: true
  - type: input
    id: users
    attributes:
      label: Users
      description: Your User Name
      placeholder: provide user
    validations:
      required: true
